<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User; // Assuming User model is in App\Models namespace

class Onboarding extends Model
{
    /**
     * Only these fields are mass-assignable.
     * Notably excluded: id, user_id, stripe_charge_id, created_at, updated_at
     * — these must be set explicitly in code, never from user input.
     */
    protected $fillable = [
        'category',
        'practice_name',
        'practitioner_name',
        'credentials',
        'specialties',
        'practice_type',
        'years_experience',
        'primary_email',
        'contact_phone',
        'address',
        'regions_served',
        'timezone',
        'ideal_audience',
        'patient_problem',
        'niche_focus',
        'brand_tone',
        'liked_websites',
        'brand_colors',
        'logo_path',
        'education',
        'certifications',
        'board_certifications',
        'memberships',
        'awards',
        'media_features',
        'cv_path',
        'short_bio',
        'full_story',
        'work_motivation',
        'personal_mission',
        'services',
        'testimonials',
        'website_goals',
        'required_pages',
        'booking_url',
        'crm_tool',
        'payment_processor',
        'patient_portal_url',
        'social_links',
        'headshot_path',
        'lead_magnets_path',
        'media_logos_path',
        'other_assets_path',
        'clinic_images_path',
        'hipaa_compliant',
        'has_privacy_policy',
        'has_terms',
        'medical_disclaimer',
        'privacy_policy_type',
        'terms_condition_type',
        'final_notes',
        'competitors_admired',
        'deadline_expectations',
        'current_step',
        'key_achievements',
        'numbers_impact',
        'partner_orgs',
        'grants_funding',
        'media_coverage',
        'training_programs',
        'affiliations',
        'podcasts',
        'past_clients',
        'degrees',
        'grants',
        'press_mentions',
        'board_roles',
        'media_mentions',
        'publications',
        'speaking_engagements',
        'conferences',
        'open_source',
        'media_awards',
        'why_this_work',
        'current_programs',
        'past_initiatives',
        'geographic_reach',
        'signature_topics',
        'results_impact',
        'case_studies',
        'research_focus',
        'ongoing_work',
        'impact_statement',
        'career_milestones',
        'business_outcomes',
        'notable_projects',
        'innovation_details',
        'metrics_impact',
        'donation_link',
        'newsletter_signup',
        'volunteer_form',
        'event_registration',
        'google_scholar',
        'orcid',
        'research_gate',
        'demo_link',
        'github_link',
        'linkedin',
        'existing_content_path',
        'public_email',
        'inquiry_types',
        'seo_keywords',
        'target_industries',
        'target_regions',
    ];

    protected $casts = [
        'specialties' => 'array',
        'ideal_audience' => 'array',
        'practice_type' => 'array',
        'services' => 'array',
        'testimonials' => 'array',
        'website_goals' => 'array',
        'required_pages' => 'array',
        'hipaa_compliant' => 'boolean',
        'has_privacy_policy' => 'boolean',
        'has_terms' => 'boolean',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

